Definitions for W3C's Web Locks API - browser externs
google/closure-compiler pull request #4156
Opened 2024-02-29 01:02 UTC by ecrider

Added browser externs for Web Locks API - based on definitions from latest W3C draft
[](https://www.w3.org/TR/2023/WD-web-locks-20230105/). The coverage is already great and API synergy with web workers cannot be overstated. Feel free to poke holes in it.

2024-02-29 19:01 UTC, lauraharker requested changes
Thanks for the contribution!

2024-12-27 19:45 UTC, brad4d commented
I've just discovered that we actually already have an externs file for these declarations, but for some unknown reason it isn't currently being exported to GitHub.

I think this is a historical accident, so I'm going to try to get it exported to GitHub instead of accepting this PR.

2024-12-28 01:03 UTC, ecrider commented
> I've just discovered that we actually already have an externs file for these declarations, but for some unknown reason it isn't currently being exported to GitHub.
> 
> I think this is a historical accident, so I'm going to try to get it exported to GitHub instead of accepting this PR.

Sure, whatever helps. I just want those definitions to end up in my production pipeline without forking official repository - whatever it will be by my contribution or someone else's doesn't matter to me much.

2024-12-30 16:49 UTC, brad4d commented
OK, https://github.com/google/closure-compiler/blob/master/externs/browser/weblocksapi.js now exists, so I'll close this PR.

@ecrider, thanks for showing us that this was missing.

2024-12-30 16:49 UTC, closed without merging